# Generated by Django 4.2 on 2024-10-07 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppleHealthStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('body_mass', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('body_fat_percentage', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('biological_sex', models.CharField(blank=True, max_length=32, null=True)),
                ('activity_move_mode', models.CharField(blank=True, max_length=128, null=True)),
                ('step_count', models.PositiveIntegerField(blank=True, null=True)),
                ('basal_energy_burned', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('active_energy_burned', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('flights_climbed', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('apple_exercise_time', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('apple_move_time', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('apple_stand_hour', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('menstrual_flow', models.CharField(blank=True, max_length=128, null=True)),
                ('hk_workout_type_identifier', models.CharField(blank=True, max_length=128, null=True)),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('oxygen_saturation', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mindful_session', models.JSONField(blank=True, null=True)),
                ('sleep_analysis', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apple_health_stat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
