# Generated by Django 5.1.2 on 2024-10-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('availability', models.JSONField()),
                ('behavior', models.FloatField()),
                ('expertise', models.FloatField()),
                ('feedback_sentiment', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_open', models.BooleanField(default=True)),
                ('distance', models.FloatField()),
                ('address', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('comfort', models.FloatField()),
                ('staff_behavior', models.FloatField()),
                ('treatment_score', models.FloatField()),
            ],
        ),
    ]
