# Generated by Django 5.1.2 on 2024-11-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0005_alter_hospital_operating_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='hospital_latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital_longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
