# Generated by Django 5.1.2 on 2024-11-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0006_doctor_hospital_latitude_doctor_hospital_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='availability',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='behavior',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='expertise',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='feedback_sentiment',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='doctor',
            unique_together={('name', 'hospital_longitude', 'hospital_latitude')},
        ),
    ]
