# Generated by Django 5.1.2 on 2024-11-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0007_alter_doctor_availability_alter_doctor_behavior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='hospital_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
