# Generated by Django 5.1.2 on 2024-11-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0008_doctor_hospital_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='hospital_website',
            field=models.CharField(default='', max_length=255),
        ),
    ]
