# Generated by Django 5.1.2 on 2024-11-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0009_doctor_hospital_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='women_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospital',
            name='women_friendly',
            field=models.BooleanField(default=False),
        ),
    ]
