name: Deploy to EC2

on:
  push:
    branches:
      - production

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy Frontend to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          cd ~
          pwd && ls
          cd AI-HealthCare
          git pull origin production
          cd frontend
          npm install
          npm run build
          # Check if the app is running and stop it if it is
          if pm2 list | grep -q "app-aihealthcare"; then
            pm2 stop app-aihealthcare
          fi
          pm2 start npm --name "app-aihealthcare" -- run start -- -H 0.0.0.0 -p 4000
          pm2 save
          EOF


  deploy_backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy Backend to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          cd ~
          pwd && ls
          cd AI-HealthCare
          git pull origin production
          source backend/venv/bin/activate
          pip install -r backend/requirements.txt
          export PYTHONPATH=. && python3 backend/manage.py migrate
          # Check if the app is running and stop it if it is
          if pm2 list | grep -q "app-aihealthcareapi"; then
            pm2 stop app-aihealthcareapi
          fi
          pm2 start python3 --name "app-aihealthcareapi" -- manage.py runserver 0.0.0.0:4001
          pm2 save
          EOF
